### ISSUE TITLE
SSH Examples Page Displays Additional Files

### ISSUE THREAD

**Issue by nigthknight** [secureCodeBox/securecodebox.github.io#11]
If you look at the integrations page for SSH you will notice that the examples display `scan.yaml` and `findings.yaml` files that does not belong to the SSH scanner

**Steps to reproduce**
1. Go to SSH scanner integrations page
2. Scroll to `Examples`

**Expected**
Only examples for SSH scan are shown (one finding.yaml/scan.yaml per target)

**What happend**
There were additional findings.yaml and scan.yaml for the `demo-app-ssh` target

**Comment by SirDany** [comment]
The additionial examples didn't show up, more preciseley, no examples showed up. This and the original bug probably as well, were related to a naming inconsistency. Since the true name of the SSH scanner is ssh_scan, this name is used throughout all filepaths, just not for the title in the frontmatter of the readme. Due to this inconsitency, the path in the frontmatter was named also simply `scanners/ssh` instead of `scanners/ssh_scan`.
